"""Catalog-backed realization tables for the draft factory.

Rows differ in food / portion / ledger geometry. Paraphrases are not new
rows. Grams are never stored: `resolve_portion` and `ledger_totals` compute
them. A row whose phrase does not resolve is invalid and must not be listed.
"""

from .checks import (
    assert_constrain_rows,
    assert_evaluate_rows,
    assert_fuzzy_resolves,
    assert_leftover_rows,
    assert_log_situation_rows,
    assert_recommend_rows,
    assert_update_rows,
)
from .tables import (
    CONSTRAIN_ROWS,
    EVALUATE_ROWS,
    FUZZY_ROWS,
    LEDGER_GAP_ROWS,
    LEFTOVER_ROWS,
    MULTI_ITEM_LOG_ROWS,
    NEAR_SYNONYM_ROWS,
    RECOMMEND_ROWS,
    UNIT_CONVERT_ROWS,
    UPDATE_ROWS,
)
from .types import (
    ConstrainRow,
    EvaluateRow,
    FuzzyRow,
    LedgerGapRow,
    LeftoverRow,
    MultiItemLogRow,
    NearSynonymRow,
    RecommendRow,
    UnitConvertRow,
    UpdateRow,
    constrain_key,
    evaluate_key,
    evaluate_windows,
    fuzzy_key,
    ledger_gap_key,
    leftover_key,
    multi_item_log_key,
    near_synonym_key,
    recommend_key,
    unit_convert_key,
    update_key,
)

__all__ = [
    "FuzzyRow",
    "MultiItemLogRow",
    "UnitConvertRow",
    "NearSynonymRow",
    "LedgerGapRow",
    "LeftoverRow",
    "UpdateRow",
    "ConstrainRow",
    "EvaluateRow",
    "RecommendRow",
    "FUZZY_ROWS",
    "MULTI_ITEM_LOG_ROWS",
    "UNIT_CONVERT_ROWS",
    "NEAR_SYNONYM_ROWS",
    "LEDGER_GAP_ROWS",
    "LEFTOVER_ROWS",
    "UPDATE_ROWS",
    "CONSTRAIN_ROWS",
    "EVALUATE_ROWS",
    "RECOMMEND_ROWS",
    "fuzzy_key",
    "multi_item_log_key",
    "unit_convert_key",
    "near_synonym_key",
    "ledger_gap_key",
    "leftover_key",
    "update_key",
    "constrain_key",
    "evaluate_key",
    "recommend_key",
    "evaluate_windows",
    "assert_fuzzy_resolves",
    "assert_log_situation_rows",
    "assert_leftover_rows",
    "assert_update_rows",
    "assert_constrain_rows",
    "assert_evaluate_rows",
    "assert_recommend_rows",
]
