from __future__ import annotations

from ..types import ConstrainRow

_MEAL = {"kcal": (400.0, 800.0), "protein_g": (20.0, 50.0)}

CONSTRAIN_ROWS: tuple[ConstrainRow, ...] = (
    ConstrainRow(
        "co-gold-shrimp",
        "condition",
        "I was thinking of having shrimp tonight. Is that okay for me, or what should I have instead?",
        ("shellfish",),
        _MEAL,
        food_id="shrimp",
        source="gold",
    ),
    ConstrainRow(
        "co-gold-pb",
        "condition",
        "Is peanut butter okay for me, or what should I have instead?",
        ("peanut",),
        _MEAL,
        food_id="peanut_butter",
        source="gold",
    ),
    ConstrainRow(
        "co-gold-conflict",
        "conflict",
        "Can you make a day of eating that hits my protein target without going over calories?",
        (),
        {"kcal": (0.0, 100.0), "protein_g": (100.0, 200.0)},
        last_plan=(("chicken_breast", 200.0),),
        source="gold",
    ),
    ConstrainRow(
        "co-milk",
        "condition",
        "I was thinking of having a glass of milk tonight. Is that okay for me, or what should I have instead?",
        ("milk",),
        {"kcal": (350.0, 750.0), "protein_g": (15.0, 45.0)},
        food_id="milk_whole",
    ),
    ConstrainRow(
        "co-tofu",
        "condition",
        "Is tofu okay for me, or what should I have instead?",
        ("soy",),
        {"kcal": (300.0, 700.0), "protein_g": (10.0, 40.0)},
        food_id="tofu",
    ),
    ConstrainRow(
        "co-eggs",
        "condition",
        "I was thinking of having scrambled eggs tonight. Is that okay for me, or what should I have instead?",
        ("egg",),
        {"kcal": (400.0, 800.0), "protein_g": (25.0, 55.0)},
        food_id="egg",
    ),
    ConstrainRow(
        "co-salmon",
        "condition",
        "Is salmon okay for me tonight, or what should I have instead?",
        ("fish",),
        {"kcal": (450.0, 800.0), "protein_g": (25.0, 55.0)},
        food_id="salmon",
    ),
    ConstrainRow(
        "co-almonds",
        "condition",
        "I was thinking of having almonds as a snack. Is that okay for me, or what should I have instead?",
        ("tree_nut",),
        {"kcal": (300.0, 650.0), "protein_g": (10.0, 35.0)},
        food_id="almond",
    ),
    ConstrainRow(
        "co-peanuts",
        "condition",
        "Are peanuts okay for me, or what should I have instead?",
        ("peanut",),
        {"kcal": (350.0, 700.0), "protein_g": (15.0, 40.0)},
        food_id="peanut",
    ),
    ConstrainRow(
        "co-soy-milk",
        "condition",
        "I was thinking of having a glass of soy milk tonight. Is that okay for me, or what should I have instead?",
        ("soy",),
        {"kcal": (350.0, 720.0), "protein_g": (12.0, 42.0)},
        food_id="soy_milk",
    ),
    ConstrainRow(
        "co-cheddar",
        "condition",
        "I was thinking of putting cheddar on dinner. Is that okay for me, or what should I have instead?",
        ("milk",),
        {"kcal": (400.0, 800.0), "protein_g": (20.0, 50.0)},
        food_id="cheddar",
    ),
    ConstrainRow(
        "co-yogurt",
        "condition",
        "Is Greek yogurt a good snack for me, or should I pick something else?",
        ("milk",),
        {"kcal": (300.0, 650.0), "protein_g": (12.0, 40.0)},
        food_id="greek_yogurt",
    ),
    ConstrainRow(
        "co-tuna",
        "condition",
        "Would a tuna plate work for lunch, or what should I have instead?",
        ("fish",),
        {"kcal": (400.0, 750.0), "protein_g": (20.0, 50.0)},
        food_id="tuna",
    ),
    ConstrainRow(
        "co-pasta",
        "condition",
        "I was craving pasta tonight. Is that okay for me, or what should I have instead?",
        ("wheat",),
        {"kcal": (400.0, 800.0), "protein_g": (20.0, 50.0)},
        food_id="pasta",
    ),
    ConstrainRow(
        "co-bread",
        "condition",
        "Can I have whole wheat bread with dinner, or what should I have instead?",
        ("gluten",),
        {"kcal": (350.0, 700.0), "protein_g": (15.0, 45.0)},
        food_id="whole_wheat_bread",
    ),
    ConstrainRow(
        "co-soy-sauce",
        "condition",
        "Is it alright if I cook with soy sauce tonight, or what should I have instead?",
        ("soy",),
        {"kcal": (400.0, 780.0), "protein_g": (20.0, 50.0)},
        food_id="2707442",
    ),
    ConstrainRow(
        "co-crab",
        "condition",
        "I was looking at crab for dinner. Is that okay for me, or what should I have instead?",
        ("shellfish",),
        {"kcal": (400.0, 800.0), "protein_g": (25.0, 55.0)},
        food_id="2706344",
    ),
    ConstrainRow(
        "co-cashew-butter",
        "condition",
        "Is cashew butter okay on breakfast, or what should I have instead?",
        ("tree_nut",),
        {"kcal": (300.0, 650.0), "protein_g": (10.0, 40.0)},
        food_id="2707536",
    ),
    ConstrainRow(
        "co-wheat-bran",
        "condition",
        "I was thinking of adding wheat bran at breakfast. Is that okay for me, or what should I have instead?",
        ("wheat",),
        {"kcal": (350.0, 720.0), "protein_g": (15.0, 42.0)},
        food_id="2708488",
    ),
    ConstrainRow(
        "co-cream-cheese",
        "condition",
        "I was going to spread cream cheese, regular, plain on something. Is that okay for me, or what should I have instead?",
        ("milk",),
        {"kcal": (320.0, 700.0), "protein_g": (12.0, 40.0)},
        food_id="2705760",
    ),
    ConstrainRow(
        "cf-50-70",
        "conflict",
        "These calorie and protein targets look impossible together. Can you still make a plan?",
        (),
        {"kcal": (0.0, 50.0), "protein_g": (70.0, 120.0)},
        last_plan=(("chicken_breast", 200.0),),
    ),
    ConstrainRow(
        "cf-55-75",
        "conflict",
        "I need a huge amount of protein but almost no calories. What would a day of eating look like?",
        (),
        {"kcal": (0.0, 55.0), "protein_g": (75.0, 125.0)},
        last_plan=(("beef", 150.0),),
    ),
    ConstrainRow(
        "cf-60-80",
        "conflict",
        "Please build a full day that stays inside my calorie cap and still hits protein.",
        (),
        {"kcal": (0.0, 60.0), "protein_g": (80.0, 130.0)},
        last_plan=(("salmon", 150.0),),
    ),
    ConstrainRow(
        "cf-65-85",
        "conflict",
        "My protein floor is way above what the calorie ceiling can support. Can you make it work?",
        (),
        {"kcal": (0.0, 65.0), "protein_g": (85.0, 135.0)},
        last_plan=(("tuna", 165.0),),
    ),
    ConstrainRow(
        "cf-70-90",
        "conflict",
        "Can you plan meals that hit protein without blowing the tiny calorie budget?",
        (),
        {"kcal": (0.0, 70.0), "protein_g": (90.0, 140.0)},
        last_plan=(("egg", 200.0),),
    ),
    ConstrainRow(
        "cf-75-95",
        "conflict",
        "I set a very tight calorie ceiling and a high protein floor. Make a plan anyway?",
        (),
        {"kcal": (0.0, 75.0), "protein_g": (95.0, 145.0)},
        last_plan=(("chicken_breast", 150.0),),
    ),
    ConstrainRow(
        "cf-80-100",
        "conflict",
        "Is there any mix of foods that satisfies both of these windows?",
        (),
        {"kcal": (0.0, 80.0), "protein_g": (100.0, 150.0)},
        last_plan=(("greek_yogurt", 245.0),),
    ),
    ConstrainRow(
        "cf-85-105",
        "conflict",
        "Try to build a day of eating under this calorie cap that still reaches my protein target.",
        (),
        {"kcal": (0.0, 85.0), "protein_g": (105.0, 155.0)},
        last_plan=(("oats", 200.0),),
    ),
    ConstrainRow(
        "cf-90-110",
        "conflict",
        "These windows feel contradictory — protein way up, calories almost none. Submit a plan if you can.",
        (),
        {"kcal": (0.0, 90.0), "protein_g": (110.0, 160.0)},
        last_plan=(("pasta", 280.0),),
    ),
    ConstrainRow(
        "cf-near-200-56",
        "conflict",
        "Can you put together something around 200 calories that still hits my protein target?",
        (),
        {"kcal": (0.0, 200.0), "protein_g": (56.0, 90.0)},
        last_plan=(("chicken_breast", 200.0),),
    ),
    ConstrainRow(
        "cf-near-400-111",
        "conflict",
        "I only have a 400 calorie budget left. Can you still make a high-protein meal?",
        (),
        {"kcal": (0.0, 400.0), "protein_g": (111.0, 150.0)},
        last_plan=(("salmon", 150.0),),
    ),
    ConstrainRow(
        "cf-near-800-221",
        "conflict",
        "Build me a day of eating under 800 calories that hits my protein floor.",
        (),
        {"kcal": (0.0, 800.0), "protein_g": (221.0, 300.0)},
        last_plan=(("greek_yogurt", 245.0),),
    ),
    ConstrainRow(
        "cf-fib-200-90",
        "conflict",
        "I want a huge amount of fibre without going over this calorie ceiling. Can you make it work?",
        (),
        {"kcal": (0.0, 200.0), "fiber_g": (90.0, 200.0)},
        last_plan=(("oats", 200.0),),
        mechanism="other_pair",
    ),
    ConstrainRow(
        "cf-fib-150-80",
        "conflict",
        "Is there any mix of foods that hits this fibre floor inside such a small calorie budget?",
        (),
        {"kcal": (0.0, 150.0), "fiber_g": (80.0, 160.0)},
        last_plan=(("black_beans", 200.0),),
        mechanism="other_pair",
    ),
    ConstrainRow(
        "cf-fat-400-55",
        "conflict",
        "I need more fat than this calorie cap can possibly hold. Submit a plan if you can.",
        (),
        {"kcal": (0.0, 400.0), "fat_g": (55.0, 100.0)},
        last_plan=(("olive_oil", 50.0),),
        mechanism="other_pair",
    ),
    ConstrainRow(
        "cf-fat-600-82",
        "conflict",
        "These fat and calorie windows feel like they fight each other. Can you still make a plan?",
        (),
        {"kcal": (0.0, 600.0), "fat_g": (82.0, 140.0)},
        last_plan=(("peanut_butter", 100.0),),
        mechanism="other_pair",
    ),
    ConstrainRow(
        "cf-fib-carb-40-45",
        "conflict",
        "I want more fibre than the carb ceiling can support. What would a day of eating look like?",
        (),
        {"carb_g": (0.0, 40.0), "fiber_g": (45.0, 80.0)},
        last_plan=(("broccoli", 200.0),),
        mechanism="other_pair",
    ),
    ConstrainRow(
        "cf-near-250-70",
        "conflict",
        "Can you put together something around 250 calories that still hits my protein target?",
        (),
        {"kcal": (0.0, 250.0), "protein_g": (70.0, 110.0)},
        last_plan=(("chicken_breast", 180.0),),
        mechanism="near_miss",
    ),
    ConstrainRow(
        "cf-near-350-97",
        "conflict",
        "I only have a 350 calorie budget left. Can you still make a high-protein meal?",
        (),
        {"kcal": (0.0, 350.0), "protein_g": (97.0, 140.0)},
        last_plan=(("tuna", 165.0),),
        mechanism="near_miss",
    ),
    ConstrainRow(
        "cf-near-180-50",
        "conflict",
        "Fifty grams of protein in a very small calorie box. Make a plan anyway?",
        (),
        {"kcal": (0.0, 180.0), "protein_g": (50.0, 80.0)},
        last_plan=(("egg", 200.0),),
        mechanism="near_miss",
    ),
    ConstrainRow(
        "cf-near-fib-250-90",
        "conflict",
        "Can you hit this fibre target without going over about 250 calories?",
        (),
        {"kcal": (0.0, 250.0), "fiber_g": (90.0, 150.0)},
        last_plan=(("oats", 150.0),),
        mechanism="near_miss",
    ),
    ConstrainRow(
        "cf-near-fat-500-67",
        "conflict",
        "I need a lot of fat in a 500 calorie budget. Is there any mix that works?",
        (),
        {"kcal": (0.0, 500.0), "fat_g": (67.0, 120.0)},
        last_plan=(("olive_oil", 40.0),),
        mechanism="near_miss",
    ),
)
