from __future__ import annotations

from ..types import FuzzyRow

# Gold-derived first so the factory still covers the calibration shapes.
# New rows after that are candidates for v0.1.
FUZZY_ROWS: tuple[FuzzyRow, ...] = (
    FuzzyRow("fz-milk-half-cup", "milk_whole", "half a cup",
             "I had half a cup of milk with breakfast — can you log that?",
             "today-breakfast", source="gold"),
    FuzzyRow("fz-eggs-two-piece", "egg", "two pieces",
             "I had two eggs this morning — can you log that?",
             "today-breakfast", source="gold"),
    FuzzyRow("fz-banana-piece", "banana", "a piece",
             "Just ate a banana as a snack — can you log it?",
             "today-snack", source="gold"),
    FuzzyRow("fz-yogurt-cup", "greek_yogurt", "a cup",
             "Had a cup of Greek yogurt as a snack. Please log it.",
             "today-snack", source="gold"),
    FuzzyRow("fz-oil-tbsp", "olive_oil", "a tablespoon",
             "I put a tablespoon of olive oil on my salad at lunch. Log that?",
             "today-lunch", source="gold"),
    FuzzyRow("fz-milk-cup", "milk_whole", "a cup",
             "I drank a cup of whole milk with breakfast. Please log it.",
             "today-breakfast"),
    FuzzyRow("fz-oats-cup", "oats", "a cup",
             "Breakfast was a cup of oats. Can you log that?",
             "today-breakfast"),
    FuzzyRow("fz-yogurt-half", "greek_yogurt", "half a cup",
             "Snack was half a cup of Greek yogurt. Log it for me.",
             "today-snack"),
    FuzzyRow("fz-oil-tsp", "olive_oil", "a teaspoon",
             "I added a teaspoon of olive oil at lunch. Please log it.",
             "today-lunch"),
    FuzzyRow("fz-cheddar-slice", "cheddar", "a slice",
             "Had a slice of cheddar at lunch — can you log that?",
             "today-lunch"),
    FuzzyRow("fz-orange-slice", "orange", "a slice",
             "I ate a slice of orange as a snack. Log it?",
             "today-snack"),
    FuzzyRow("fz-avocado-slice", "avocado", "a slice",
             "Put a slice of avocado on my lunch. Please log that.",
             "today-lunch"),
    FuzzyRow("fz-apple-piece", "apple", "a piece",
             "Just ate an apple as a snack — can you log it?",
             "today-snack"),
    FuzzyRow("fz-tofu-cup", "tofu", "a cup",
             "Lunch was a cup of tofu. Please log it.",
             "today-lunch"),
    FuzzyRow("fz-pasta-cup", "pasta", "a cup",
             "I had a cup of pasta for dinner. Log that?",
             "today-dinner"),
    FuzzyRow("fz-beans-cup", "black_beans", "a cup",
             "Had a cup of black beans at lunch. Can you log that?",
             "today-lunch"),
    FuzzyRow("fz-soymilk-half", "soy_milk", "half a cup",
             "I had half a cup of soy milk with breakfast. Please log it.",
             "today-breakfast"),
    FuzzyRow("fz-spinach-cup", "spinach", "a cup",
             "Dinner side was a cup of spinach. Log it for me.",
             "today-dinner"),
    FuzzyRow("fz-pb-tbsp", "peanut_butter", "a tablespoon",
             "I had a tablespoon of peanut butter at breakfast. Please log it.",
             "today-breakfast"),
    FuzzyRow("fz-tuna-can", "tuna", "a can",
             "Logged lunch already? I ate a can of tuna. Please add it.",
             "today-lunch"),
    FuzzyRow("fz-potato-piece", "potato", "a piece",
             "I had a baked potato for dinner. Can you log that?",
             "today-dinner"),
    FuzzyRow("fz-almond-half", "almond", "half a cup",
             "Snack was half a cup of almonds. Please log it.",
             "today-snack"),
    FuzzyRow("fz-rice-half", "white_rice", "half a cup",
             "I had half a cup of white rice at dinner. Log that?",
             "today-dinner"),
    FuzzyRow("fz-oats-oz", "oats", "2 ounces",
             "Snack was about 2 ounces of oats. Log it for me.",
             "today-snack", source="gold"),
    # v0.6 dish sample: real users name the dish and say "a serving", not
    # grams. Each row resolves through the catalog default FNDDS portion via
    # the "serving" unit or the dish-noun grammar in portions.py; the oracle
    # is still a single exact gram value, so the binary Pass rule holds.
    FuzzyRow("fz-dish-sandwich", "2706880", "a sandwich",
             "Lunch was a sandwich — can you log it?",
             "today-lunch", source="v0.6-dish-sample"),
    FuzzyRow("fz-dish-bbq-beef-sandwich", "2706885", "a barbecue beef sandwich",
             "I had a barbecue beef sandwich for lunch. Log that?",
             "today-lunch", source="v0.6-dish-sample"),
    FuzzyRow("fz-dish-burrito", "2708534", "a burrito",
             "Dinner was a burrito — please log it.",
             "today-dinner", source="v0.6-dish-sample"),
    FuzzyRow("fz-dish-egg-foo-yung", "2707196", "a serving of shrimp egg foo yung",
             "I had shrimp egg foo yung at dinner, one serving. Can you log that?",
             "today-dinner", source="v0.6-dish-sample"),
    FuzzyRow("fz-dish-omelet", "2707198", "an omelet",
             "Breakfast was an omelet. Please log it.",
             "today-breakfast", source="v0.6-dish-sample"),
    FuzzyRow("fz-dish-lasagna", "2708750", "a serving of lasagna",
             "Dinner was lasagna, one serving. Log it for me.",
             "today-dinner", source="v0.6-dish-sample"),
    FuzzyRow("fz-dish-soup", "2709144", "a bowl of soup",
             "Had a bowl of soup for lunch — can you log it?",
             "today-lunch", source="v0.6-dish-sample"),
    FuzzyRow("fz-dish-curry", "2706437", "a serving of chicken curry",
             "I had chicken curry for dinner, about a serving. Please log it.",
             "today-dinner", source="v0.6-dish-sample"),
    FuzzyRow("fz-dish-fried-rice", "167668", "a serving of fried rice",
             "Lunch was fried rice from the Chinese place. Log it?",
             "today-lunch", source="v0.6-dish-sample"),
    FuzzyRow("fz-dish-chili", "2706373", "a bowl of chili",
             "I had a bowl of chili for dinner. Can you log that?",
             "today-dinner", source="v0.6-dish-sample"),
)
