from __future__ import annotations

from ..types import LeftoverRow

_E = {"kcal": (1800.0, 2200.0), "protein_g": (80.0, 160.0)}
_CUT = {"kcal": (1600.0, 1900.0), "protein_g": (110.0, 160.0)}
_HIGHP = {"kcal": (1800.0, 2200.0), "protein_g": (120.0, 180.0)}

LEFTOVER_ROWS: tuple[LeftoverRow, ...] = (
    LeftoverRow(
        "lo-gold-early",
        "I already ate breakfast and lunch. What should I eat?",
        {"kcal": (1800.0, 2200.0), "protein_g": (80.0, 160.0)},
        (
            ("oats", 80.0, "today-breakfast"),
            ("banana", 118.0, "today-breakfast"),
            ("milk_whole", 244.0, "today-breakfast"),
            ("chicken_breast", 200.0, "today-lunch"),
            ("white_rice", 300.0, "today-lunch"),
            ("olive_oil", 20.0, "today-lunch"),
            ("cheddar", 40.0, "today-lunch"),
        ),
        source="gold",
    ),
    LeftoverRow(
        "lo-gold-three-meals",
        "I already ate breakfast, lunch, and a snack. Can I still eat something?",
        {"kcal": (1800.0, 2200.0), "protein_g": (80.0, 160.0)},
        (
            ("oats", 80.0, "today-breakfast"),
            ("banana", 118.0, "today-breakfast"),
            ("milk_whole", 244.0, "today-breakfast"),
            ("beef", 180.0, "today-lunch"),
            ("pasta", 280.0, "today-lunch"),
            ("olive_oil", 18.0, "today-lunch"),
            ("spinach", 90.0, "today-lunch"),
            ("greek_yogurt", 200.0, "today-snack"),
            ("apple", 182.0, "today-snack"),
        ),
        source="gold",
    ),
    LeftoverRow(
        "lo-gold-cut",
        "I'm cutting and I already ate breakfast and lunch. What can I still eat?",
        {"kcal": (1600.0, 1900.0), "protein_g": (110.0, 160.0)},
        (
            ("oats", 60.0, "today-breakfast"),
            ("greek_yogurt", 170.0, "today-breakfast"),
            ("banana", 118.0, "today-breakfast"),
            ("chicken_breast", 90.0, "today-lunch"),
            ("white_rice", 250.0, "today-lunch"),
            ("broccoli", 100.0, "today-lunch"),
            ("olive_oil", 12.0, "today-lunch"),
            ("cheddar", 40.0, "today-lunch"),
            ("potato", 200.0, "today-lunch"),
        ),
        source="gold",
        plan_preset={"goal": "cut"},
    ),
    LeftoverRow(
        "lo-breakfast-only",
        "I only had breakfast. What should I eat for the rest of the day?",
        {"kcal": (1800.0, 2200.0), "protein_g": (80.0, 160.0)},
        (
            ("oats", 80.0, "today-breakfast"),
            ("banana", 118.0, "today-breakfast"),
            ("milk_whole", 244.0, "today-breakfast"),
        ),
    ),
    LeftoverRow(
        "lo-protein-debt",
        "I already ate breakfast and lunch. I still want to hit protein.",
        {"kcal": (1800.0, 2200.0), "protein_g": (120.0, 180.0)},
        (
            ("white_rice", 300.0, "today-breakfast"),
            ("banana", 126.0, "today-breakfast"),
            ("apple", 182.0, "today-breakfast"),
            ("pasta", 200.0, "today-lunch"),
            ("olive_oil", 15.0, "today-lunch"),
            ("broccoli", 150.0, "today-lunch"),
        ),
    ),
    LeftoverRow(
        "lo-protein-met",
        "I already ate a high-protein breakfast and lunch. What should I eat for the rest of the day?",
        {"kcal": (1800.0, 2200.0), "protein_g": (80.0, 160.0)},
        (
            ("egg", 100.0, "today-breakfast"),
            ("greek_yogurt", 245.0, "today-breakfast"),
            ("chicken_breast", 220.0, "today-lunch"),
            ("spinach", 80.0, "today-lunch"),
        ),
    ),
    LeftoverRow(
        "lo-snack-no-lunch",
        "I had breakfast and a snack but skipped lunch. What should I eat for the rest of the day?",
        {"kcal": (1800.0, 2200.0), "protein_g": (80.0, 160.0)},
        (
            ("oats", 80.0, "today-breakfast"),
            ("milk_whole", 244.0, "today-breakfast"),
            ("greek_yogurt", 200.0, "today-snack"),
            ("apple", 182.0, "today-snack"),
        ),
    ),
    LeftoverRow(
        "lo-tofu-lunch",
        "I already ate breakfast and a tofu lunch. What should I eat for the rest of the day?",
        {"kcal": (1800.0, 2200.0), "protein_g": (80.0, 160.0)},
        (
            ("soy_milk", 244.0, "today-breakfast"),
            ("oats", 80.0, "today-breakfast"),
            ("tofu", 200.0, "today-lunch"),
            ("black_beans", 172.0, "today-lunch"),
            ("white_rice", 200.0, "today-lunch"),
        ),
    ),
    LeftoverRow(
        "lo-almost-full",
        "I already ate breakfast, lunch, and a snack. Is there room for anything else?",
        {"kcal": (1800.0, 2200.0), "protein_g": (80.0, 160.0)},
        (
            ("oats", 80.0, "today-breakfast"),
            ("banana", 118.0, "today-breakfast"),
            ("milk_whole", 244.0, "today-breakfast"),
            ("chicken_breast", 180.0, "today-lunch"),
            ("white_rice", 280.0, "today-lunch"),
            ("olive_oil", 18.0, "today-lunch"),
            ("greek_yogurt", 200.0, "today-snack"),
            ("apple", 182.0, "today-snack"),
        ),
    ),
    LeftoverRow(
        "lo-cut-salmon",
        "I'm cutting and already ate breakfast and lunch. What should I eat for the rest of the day?",
        {"kcal": (1600.0, 1900.0), "protein_g": (110.0, 160.0)},
        (
            ("oats", 60.0, "today-breakfast"),
            ("greek_yogurt", 170.0, "today-breakfast"),
            ("salmon", 150.0, "today-lunch"),
            ("broccoli", 120.0, "today-lunch"),
            ("olive_oil", 10.0, "today-lunch"),
        ),
        plan_preset={"goal": "cut"},
    ),
    LeftoverRow(
        "lo-beans-rice",
        "Breakfast and a beans-and-rice lunch are already logged. What should I eat for the rest of the day?",
        {"kcal": (1800.0, 2200.0), "protein_g": (80.0, 160.0)},
        (
            ("oats", 80.0, "today-breakfast"),
            ("banana", 126.0, "today-breakfast"),
            ("black_beans", 172.0, "today-lunch"),
            ("white_rice", 250.0, "today-lunch"),
            ("avocado", 75.0, "today-lunch"),
        ),
    ),
    LeftoverRow(
        "lo-tuna-lunch",
        "I already ate breakfast and a tuna lunch. What should I eat for the rest of the day?",
        _E,
        (
            ("oats", 80.0, "today-breakfast"),
            ("banana", 126.0, "today-breakfast"),
            ("tuna", 165.0, "today-lunch"),
            ("spinach", 50.0, "today-lunch"),
            ("white_rice", 158.0, "today-lunch"),
        ),
    ),
    LeftoverRow(
        "lo-avocado-rice",
        "Breakfast and an avocado-and-rice lunch are already logged. What should I eat for the rest of the day?",
        _E,
        (
            ("soy_milk", 244.0, "today-breakfast"),
            ("oats", 80.0, "today-breakfast"),
            ("avocado", 150.0, "today-lunch"),
            ("white_rice", 200.0, "today-lunch"),
            ("black_beans", 172.0, "today-lunch"),
        ),
    ),
    LeftoverRow(
        "lo-dinner-logged",
        "I already ate breakfast, lunch, and dinner. Is there room for a late bite?",
        _E,
        (
            ("oats", 80.0, "today-breakfast"),
            ("banana", 126.0, "today-breakfast"),
            ("milk_whole", 244.0, "today-breakfast"),
            ("chicken_breast", 180.0, "today-lunch"),
            ("white_rice", 250.0, "today-lunch"),
            ("olive_oil", 15.0, "today-lunch"),
            ("pasta", 200.0, "today-dinner"),
            ("beef", 150.0, "today-dinner"),
            ("spinach", 80.0, "today-dinner"),
        ),
    ),
    LeftoverRow(
        "lo-skip-breakfast",
        "I skipped breakfast and already ate lunch. What should I eat for the rest of the day?",
        _E,
        (
            ("chicken_breast", 200.0, "today-lunch"),
            ("white_rice", 250.0, "today-lunch"),
            ("broccoli", 150.0, "today-lunch"),
            ("olive_oil", 15.0, "today-lunch"),
        ),
    ),
    LeftoverRow(
        "lo-almond-snack",
        "I already ate breakfast, lunch, and a handful of almonds. What should I eat for the rest of the day?",
        _E,
        (
            ("oats", 80.0, "today-breakfast"),
            ("banana", 126.0, "today-breakfast"),
            ("chicken_breast", 160.0, "today-lunch"),
            ("broccoli", 120.0, "today-lunch"),
            ("almond", 36.0, "today-snack"),
        ),
    ),
    LeftoverRow(
        "lo-peanut-allergy",
        "Breakfast and lunch are already in. What can I still eat for the rest of the day?",
        _E,
        (
            ("oats", 80.0, "today-breakfast"),
            ("banana", 126.0, "today-breakfast"),
            ("chicken_breast", 180.0, "today-lunch"),
            ("white_rice", 200.0, "today-lunch"),
            ("broccoli", 100.0, "today-lunch"),
        ),
        allergies=("peanut",),
    ),
    LeftoverRow(
        "lo-milk-allergy",
        "I already logged breakfast and lunch. What should I eat for the rest of the day?",
        _E,
        (
            ("soy_milk", 244.0, "today-breakfast"),
            ("oats", 80.0, "today-breakfast"),
            ("apple", 200.0, "today-breakfast"),
            ("chicken_breast", 170.0, "today-lunch"),
            ("potato", 230.0, "today-lunch"),
            ("spinach", 80.0, "today-lunch"),
        ),
        allergies=("milk",),
    ),
    LeftoverRow(
        "lo-cut-tight",
        "I'm cutting and I already ate breakfast, lunch, and a snack. What should I eat for the rest of the day?",
        _CUT,
        (
            ("oats", 60.0, "today-breakfast"),
            ("greek_yogurt", 170.0, "today-breakfast"),
            ("chicken_breast", 150.0, "today-lunch"),
            ("white_rice", 200.0, "today-lunch"),
            ("broccoli", 100.0, "today-lunch"),
            ("olive_oil", 10.0, "today-lunch"),
            ("apple", 200.0, "today-snack"),
        ),
        plan_preset={"goal": "cut"},
    ),
    LeftoverRow(
        "lo-potato-lunch",
        "I already ate breakfast and a potato lunch. What should I eat for the rest of the day?",
        _E,
        (
            ("oats", 80.0, "today-breakfast"),
            ("banana", 126.0, "today-breakfast"),
            ("potato", 230.0, "today-lunch"),
            ("cheddar", 42.0, "today-lunch"),
            ("broccoli", 100.0, "today-lunch"),
        ),
    ),
    LeftoverRow(
        "lo-pb-breakfast",
        "I only had breakfast — oats with peanut butter. What should I eat for the rest of the day?",
        _E,
        (
            ("oats", 80.0, "today-breakfast"),
            ("peanut_butter", 32.0, "today-breakfast"),
            ("banana", 126.0, "today-breakfast"),
        ),
    ),
    LeftoverRow(
        "lo-beef-pasta",
        "Breakfast and a beef-and-pasta lunch are already logged. What should I eat for the rest of the day?",
        _E,
        (
            ("greek_yogurt", 245.0, "today-breakfast"),
            ("orange", 180.0, "today-breakfast"),
            ("beef", 180.0, "today-lunch"),
            ("pasta", 280.0, "today-lunch"),
            ("spinach", 90.0, "today-lunch"),
        ),
    ),
    LeftoverRow(
        "lo-late-snack-only",
        "I've only had a snack so far. What should I eat for the rest of the day?",
        _E,
        (
            ("greek_yogurt", 200.0, "today-snack"),
            ("apple", 200.0, "today-snack"),
        ),
    ),
    LeftoverRow(
        "lo-three-carb-debt",
        "I already ate, but I still want to hit protein. What should I eat?",
        _HIGHP,
        (
            ("white_rice", 250.0, "today-breakfast"),
            ("banana", 126.0, "today-breakfast"),
            ("pasta", 280.0, "today-lunch"),
            ("olive_oil", 18.0, "today-lunch"),
            ("apple", 200.0, "today-lunch"),
            ("potato", 230.0, "today-snack"),
        ),
    ),
    LeftoverRow(
        "lo-gym-protein-in",
        "Breakfast and lunch were already high in protein. What should I eat for the rest of the day?",
        _E,
        (
            ("egg", 150.0, "today-breakfast"),
            ("greek_yogurt", 245.0, "today-breakfast"),
            ("tuna", 165.0, "today-lunch"),
            ("spinach", 80.0, "today-lunch"),
            ("chicken_breast", 150.0, "today-lunch"),
        ),
    ),
    LeftoverRow(
        "lo-shrimp-lunch",
        "I already ate breakfast and a shrimp lunch. What should I eat for the rest of the day?",
        _E,
        (
            ("oats", 80.0, "today-breakfast"),
            ("orange", 180.0, "today-breakfast"),
            ("shrimp", 200.0, "today-lunch"),
            ("white_rice", 200.0, "today-lunch"),
            ("broccoli", 100.0, "today-lunch"),
        ),
    ),
    LeftoverRow(
        "lo-cut-breakfast-only",
        "I'm cutting and I only had breakfast. What should I eat for the rest of the day?",
        _CUT,
        (
            ("oats", 60.0, "today-breakfast"),
            ("greek_yogurt", 170.0, "today-breakfast"),
            ("banana", 126.0, "today-breakfast"),
        ),
        plan_preset={"goal": "cut"},
    ),
)
