from __future__ import annotations

from ..types import RecommendRow

# Gold-shaped first so the factory still covers the calibration shapes.
RECOMMEND_ROWS: tuple[RecommendRow, ...] = (
    RecommendRow(
        "rec-safe-001",
        "Can you put together a meal that works with my targets and allergies?",
        "everyday",
        {"kcal": (400.0, 800.0), "protein_g": (25.0, 55.0)},
        allergies=("peanut", "shellfish"),
        source="gold",
        occasion="dinner",
    ),
    RecommendRow(
        "rec-cut-001",
        "I'm cutting and don't want to blow dinner. What should I eat?",
        "cut",
        {"kcal": (400.0, 600.0), "protein_g": (35.0, 55.0)},
        plan_preset={"goal": "cut"},
        source="gold",
        occasion="dinner",
    ),
    RecommendRow(
        "rec-gym-001",
        "Just finished lifting — what should I eat?",
        "gym",
        {"kcal": (400.0, 750.0), "protein_g": (35.0, 65.0)},
        plan_preset={"goal": "muscle"},
        source="gold",
        occasion="post-workout",
    ),
    RecommendRow(
        "rec-flex-001",
        "Tonight I want something more filling. Any ideas?",
        "flex",
        {"kcal": (700.0, 1200.0), "protein_g": (20.0, 80.0)},
        allergies=("peanut",),
        plan_preset={"flex_day": True},
        source="gold",
        occasion="dinner",
    ),
    RecommendRow(
        "rec-htn-001",
        "What's for dinner?",
        "htn",
        {"kcal": (400.0, 800.0), "protein_g": (20.0, 50.0), "sodium_mg": (0.0, 400.0)},
        source="gold",
        occasion="dinner",
    ),
    RecommendRow(
        "rec-snack-001",
        "I need a snack.",
        "everyday",
        {"kcal": (80.0, 250.0), "protein_g": (8.0, 25.0)},
        allergies=("peanut",),
        source="gold",
        occasion="snack",
    ),
    RecommendRow(
        "rec-bfast-wide",
        "What's a simple breakfast I can actually make?",
        "everyday",
        {"kcal": (350.0, 650.0), "protein_g": (12.0, 40.0)},
        occasion="breakfast",
    ),
    RecommendRow(
        "rec-lunch-milk",
        "I have to skip dairy. What should lunch look like?",
        "everyday",
        {"kcal": (450.0, 750.0), "protein_g": (25.0, 55.0)},
        allergies=("milk",),
        occasion="lunch",
    ),
    RecommendRow(
        "rec-dinner-egg",
        "Eggs are off the table for me. What can I have tonight?",
        "everyday",
        {"kcal": (400.0, 800.0), "protein_g": (20.0, 50.0)},
        allergies=("egg",),
        occasion="dinner",
    ),
    RecommendRow(
        "rec-lunch-fish",
        "No fish, please. What should I eat for lunch?",
        "everyday",
        {"kcal": (450.0, 700.0), "protein_g": (30.0, 55.0)},
        allergies=("fish",),
        occasion="lunch",
    ),
    RecommendRow(
        "rec-dinner-soy",
        "Soy is a no for me. What should dinner be?",
        "everyday",
        {"kcal": (400.0, 750.0), "protein_g": (20.0, 50.0)},
        allergies=("soy",),
        occasion="dinner",
    ),
    RecommendRow(
        "rec-snack-treenut",
        "I need a mid-afternoon bite and I can't do tree nuts.",
        "everyday",
        {"kcal": (100.0, 280.0), "protein_g": (8.0, 22.0)},
        allergies=("tree_nut",),
        occasion="snack",
    ),
    RecommendRow(
        "rec-lunch-wheat",
        "Wheat is out. What should I pack for lunch?",
        "everyday",
        {"kcal": (450.0, 780.0), "protein_g": (25.0, 50.0)},
        allergies=("wheat",),
        occasion="lunch",
    ),
    RecommendRow(
        "rec-dinner-gluten",
        "Keep gluten away from dinner. What should I eat?",
        "everyday",
        {"kcal": (400.0, 720.0), "protein_g": (22.0, 48.0)},
        allergies=("gluten",),
        occasion="dinner",
    ),
    RecommendRow(
        "rec-bfast-wheat-gluten",
        "Bread is a problem — wheat and gluten both. What's breakfast?",
        "everyday",
        {"kcal": (320.0, 580.0), "protein_g": (15.0, 40.0)},
        allergies=("wheat", "gluten"),
        occasion="breakfast",
    ),
    RecommendRow(
        "rec-lunch-milk-egg",
        "No dairy, no eggs. What works for lunch?",
        "everyday",
        {"kcal": (450.0, 760.0), "protein_g": (25.0, 52.0)},
        allergies=("egg", "milk"),
        occasion="lunch",
    ),
    RecommendRow(
        "rec-dinner-fish-shell",
        "Seafood of any kind is a bad idea. What's dinner?",
        "everyday",
        {"kcal": (400.0, 780.0), "protein_g": (28.0, 55.0)},
        allergies=("fish", "shellfish"),
        occasion="dinner",
    ),
    RecommendRow(
        "rec-snack-peanut-soy-tn",
        "Peanuts, soy, and tree nuts are all out. I just need a snack.",
        "everyday",
        {"kcal": (90.0, 240.0), "protein_g": (10.0, 24.0)},
        allergies=("peanut", "soy", "tree_nut"),
        occasion="snack",
    ),
    RecommendRow(
        "rec-dinner-milk-wheat-soy",
        "Dairy, wheat, and soy all bother me. What should I eat tonight?",
        "everyday",
        {"kcal": (420.0, 800.0), "protein_g": (22.0, 50.0)},
        allergies=("milk", "soy", "wheat"),
        occasion="dinner",
    ),
    RecommendRow(
        "rec-lunch-tight",
        "I only have room for a small lunch. What should I eat?",
        "everyday",
        {"kcal": (480.0, 560.0), "protein_g": (30.0, 42.0)},
        occasion="lunch",
    ),
    RecommendRow(
        "rec-dinner-sodium",
        "I want dinner that isn't a salt bomb. What should I eat?",
        "everyday",
        {"kcal": (400.0, 800.0), "protein_g": (20.0, 50.0), "sodium_mg": (0.0, 500.0)},
        allergies=("peanut",),
        occasion="dinner",
    ),
    RecommendRow(
        "rec-bfast-fiber",
        "I want breakfast that actually has some fibre. Ideas?",
        "everyday",
        {"kcal": (350.0, 600.0), "protein_g": (15.0, 40.0), "fiber_g": (6.0, 20.0)},
        occasion="breakfast",
    ),
    RecommendRow(
        "rec-lunch-fat",
        "Keep lunch on the lean side — no shellfish either. What should I eat?",
        "everyday",
        {"kcal": (450.0, 750.0), "protein_g": (25.0, 50.0), "fat_g": (0.0, 30.0)},
        allergies=("shellfish",),
        occasion="lunch",
    ),
    RecommendRow(
        "rec-snack-fiber",
        "A fibre-ish snack, and skip eggs. What have you got?",
        "everyday",
        {"kcal": (120.0, 280.0), "protein_g": (10.0, 25.0), "fiber_g": (4.0, 12.0)},
        allergies=("egg",),
        occasion="snack",
    ),
    RecommendRow(
        "rec-dinner-carb",
        "I want a carb-forward dinner. What should I eat?",
        "everyday",
        {"kcal": (500.0, 800.0), "protein_g": (20.0, 45.0), "carb_g": (40.0, 90.0)},
        occasion="dinner",
    ),
    RecommendRow(
        "rec-cut-lunch-tight",
        "I'm cutting and lunch has to stay small. What should I eat?",
        "cut",
        {"kcal": (380.0, 520.0), "protein_g": (38.0, 52.0)},
        plan_preset={"goal": "cut"},
        occasion="lunch",
    ),
    RecommendRow(
        "rec-cut-milk",
        "Cutting, and dairy is out. What's dinner?",
        "cut",
        {"kcal": (400.0, 580.0), "protein_g": (35.0, 50.0)},
        allergies=("milk",),
        plan_preset={"goal": "cut"},
        occasion="dinner",
    ),
    RecommendRow(
        "rec-cut-fiber",
        "I'm cutting and I'd like lunch with some fibre. Wheat is a no.",
        "cut",
        {"kcal": (400.0, 600.0), "protein_g": (35.0, 55.0), "fiber_g": (5.0, 18.0)},
        allergies=("wheat",),
        plan_preset={"goal": "cut"},
        occasion="lunch",
    ),
    RecommendRow(
        "rec-gym-peanut",
        "Just trained and I can't do peanuts. What should I eat?",
        "gym",
        {"kcal": (520.0, 860.0), "protein_g": (45.0, 75.0)},
        allergies=("peanut",),
        plan_preset={"goal": "muscle"},
        occasion="post-workout",
    ),
    RecommendRow(
        "rec-gym-egg-milk",
        "Need dinner after training — no eggs, no dairy.",
        "gym",
        {"kcal": (420.0, 760.0), "protein_g": (38.0, 68.0)},
        allergies=("egg", "milk"),
        plan_preset={"goal": "muscle"},
        occasion="dinner",
    ),
    RecommendRow(
        "rec-gym-sodium",
        "Post-lift meal that isn't swimming in salt. What should I eat?",
        "gym",
        {"kcal": (400.0, 750.0), "protein_g": (35.0, 65.0), "sodium_mg": (0.0, 450.0)},
        plan_preset={"goal": "muscle"},
        occasion="post-workout",
    ),
    RecommendRow(
        "rec-flex-lunch",
        "I'm starving and lunch can be a bigger plate than usual.",
        "flex",
        {"kcal": (750.0, 1250.0), "protein_g": (25.0, 85.0)},
        plan_preset={"flex_day": True},
        occasion="lunch",
    ),
    RecommendRow(
        "rec-flex-fish",
        "Flex night, but skip the fish. What should I eat?",
        "flex",
        {"kcal": (700.0, 1150.0), "protein_g": (20.0, 75.0)},
        allergies=("fish",),
        plan_preset={"flex_day": True},
        occasion="dinner",
    ),
    RecommendRow(
        "rec-flex-fat",
        "I can go bigger tonight, just not with tree nuts, and keep fat in check.",
        "flex",
        {"kcal": (720.0, 1180.0), "protein_g": (22.0, 80.0), "fat_g": (0.0, 55.0)},
        allergies=("tree_nut",),
        plan_preset={"flex_day": True},
        occasion="dinner",
    ),
    RecommendRow(
        "rec-htn-lunch",
        "What's a low-salt lunch? Peanuts are out too.",
        "htn",
        {"kcal": (400.0, 750.0), "protein_g": (22.0, 48.0), "sodium_mg": (0.0, 350.0)},
        allergies=("peanut",),
        occasion="lunch",
    ),
    RecommendRow(
        "rec-htn-milk",
        "Dinner, keep the salt down, and I can't do dairy.",
        "htn",
        {"kcal": (380.0, 720.0), "protein_g": (20.0, 50.0), "sodium_mg": (0.0, 380.0)},
        allergies=("milk",),
        occasion="dinner",
    ),
    RecommendRow(
        "rec-htn-fiber",
        "A breakfast that isn't salty and has some fibre in it?",
        "htn",
        {
            "kcal": (400.0, 800.0),
            "protein_g": (20.0, 50.0),
            "sodium_mg": (0.0, 420.0),
            "fiber_g": (5.0, 16.0),
        },
        occasion="breakfast",
    ),
    RecommendRow(
        "rec-bfast-shellfish",
        "Shellfish is a no. What's breakfast?",
        "everyday",
        {"kcal": (300.0, 550.0), "protein_g": (14.0, 38.0)},
        allergies=("shellfish",),
        occasion="breakfast",
    ),
    RecommendRow(
        "rec-snack-soy",
        "Quick snack, and keep soy out of it.",
        "everyday",
        {"kcal": (100.0, 260.0), "protein_g": (8.0, 22.0)},
        allergies=("soy",),
        occasion="snack",
    ),
    RecommendRow(
        "rec-dinner-fat-ceil",
        "Dinner that isn't greasy. What should I eat?",
        "everyday",
        {"kcal": (400.0, 700.0), "protein_g": (22.0, 50.0), "fat_g": (0.0, 25.0)},
        occasion="dinner",
    ),
)
