#!/usr/bin/env python3
"""Generate a leaderboard table from committed report JSON, so READMEs stop drifting.

Hand-transcribed tables are how the two READMEs ended up disagreeing. This renders the
table from the reports themselves and stamps every row with the three things a reader
needs to compare numbers honestly:

* **exam** — which split the run used (a number on a different exam is not comparable)
* **mode** — the harness protocol (native tool calling vs text ReAct)
* **endpoint** — the provider/gateway, because the same model id can be a different
  snapshot per endpoint

    .venv/bin/python scripts/render_leaderboard.py --reports reports --glob 'benchmark_*.json'
    .venv/bin/python scripts/render_leaderboard.py --reports reports --out /tmp/table.md
"""

from __future__ import annotations

import argparse
import json
from datetime import UTC, datetime
from pathlib import Path


def endpoint_of(url: str | None) -> str:
    if not url:
        return "—"
    for host, label in (
        ("ark.cn-beijing.volces.com", "ARK Agent Plan"),
        ("api.commandcode.ai", "Command Code"),
        ("api.deepseek.com", "DeepSeek API"),
        ("dashscope", "DashScope"),
        ("opencode", "opencode"),
        ("nvidia", "NVIDIA"),
    ):
        if host in url:
            return label
    return url.split("/")[2] if "//" in url else url


def load_rows(reports_dir: Path, pattern: str) -> list[dict]:
    rows: list[dict] = []
    for path in sorted(reports_dir.glob(pattern)):
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            continue
        if "tasks" not in data:
            continue
        total = data.get("total_tasks") or len(data.get("tasks", []))
        passed = data.get("passed_tasks")
        if passed is None or not total:
            continue
        families = data.get("family_breakdown") or {}
        rows.append(
            {
                "file": path.name,
                "model": str(data.get("model", "?")),
                "exam": Path(str(data.get("split", "?"))).name,
                "mode": data.get("contract")
                or data.get("harness_mode")
                or "text-json (unrecorded)",
                "endpoint": endpoint_of(data.get("url") or data.get("endpoint")),
                "passed": passed,
                "total": total,
                "rate": round(100.0 * passed / total, 1),
                # From the counts, like `rate`: the stored pct is already rounded to two places,
                # and re-rounding 68.25 to one place prints 68.2 beside a `rate` of 68.3.
                "clean_rate": (
                    round(100.0 * passed / data["clean_total_tasks"], 1)
                    if data.get("clean_total_tasks")
                    else data.get("clean_pass_rate_pct")
                ),
                "void": data.get("void_count", 0),
                "avg_steps": data.get("overall_avg_steps"),
                "avg_seconds": data.get("overall_avg_time_seconds"),
                "context_limit": data.get("context_limit"),
                "temperature": data.get("temperature"),
                "generated": datetime.fromtimestamp(path.stat().st_mtime, tz=UTC)
                .astimezone()
                .strftime("%Y-%m-%d %H:%M"),
                "family_breakdown": families,
            }
        )
    return rows


def render(rows: list[dict], title: str) -> str:
    if not rows:
        return "_no reports found_"

    exams = sorted({r["exam"] for r in rows})
    modes = sorted({r["mode"] for r in rows})
    endpoints = sorted({r["endpoint"] for r in rows})
    out: list[str] = []
    out.append(f"### {title}")
    out.append("")
    out.append(
        f"Exam: **{', '.join(exams)}** · harness: **{', '.join(modes)}** · "
        f"endpoint: **{', '.join(endpoints)}** · temperature: "
        f"**{', '.join(sorted({str(r['temperature']) for r in rows}))}**"
    )
    out.append("")
    out.append("| Model | Exam | Mode | Endpoint | Pass | Rate | Clean rate | Void | Avg steps | Avg s/task |")
    out.append("|:--|:--|:--|:--|--:|--:|--:|--:|--:|--:|")
    for r in sorted(rows, key=lambda r: -r["rate"]):
        clean = "—" if r["clean_rate"] is None else f"{r['clean_rate']:.1f}%"
        steps = "—" if r["avg_steps"] is None else f"{r['avg_steps']:.1f}"
        secs = "—" if r["avg_seconds"] is None else f"{r['avg_seconds']:.1f}"
        out.append(
            f"| `{r['model']}` | {r['exam']} | {r['mode']} | {r['endpoint']} | "
            f"{r['passed']}/{r['total']} | {r['rate']:.1f}% | {clean} | {r['void']} | {steps} | {secs} |"
        )
    out.append("")
    out.append("Generated by `scripts/render_leaderboard.py` from the report JSON above;")
    out.append("regenerate instead of editing by hand.")
    out.append("")

    # Duplicate rows for the same model+exam+mode are a real hazard: a stale report left
    # in the directory silently competes with a fresh one.
    seen: dict[tuple, list[dict]] = {}
    for r in rows:
        key = (r["model"], r["exam"], r["mode"], str(r["temperature"]))
        seen.setdefault(key, []).append(r)
    clashes = {k: v for k, v in seen.items() if len(v) > 1}
    if clashes:
        out.append(
            "> **Several runs found for the same model/exam/mode/temperature.** If these are "
            "deliberate repeats (a noise floor), report the spread rather than one row; if not, "
            "one of them is stale:"
        )
        for (model, exam, mode, temp), group in sorted(clashes.items()):
            scores = sorted({g["passed"] for g in group})
            detail = ", ".join(f"{g['file'].split('_')[-1][:12]}={g['passed']}/{g['total']}" for g in group)
            spread = f"spread {scores[0]}-{scores[-1]} of {group[0]['total']}" if len(scores) > 1 else "identical scores"
            out.append(f"> - `{model}` on {exam} / {mode} / T={temp}: {len(group)} runs, {spread} ({detail})")
        out.append("")
    return "\n".join(out)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--reports", default="reports", type=Path)
    parser.add_argument("--glob", default="benchmark_*.json")
    parser.add_argument("--title", default="NutriEnv leaderboard")
    parser.add_argument("--out", default=None)
    args = parser.parse_args(argv)

    rows = load_rows(args.reports, args.glob)
    table = render(rows, args.title)
    print(table)
    if args.out:
        out = Path(args.out)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(table + "\n", encoding="utf-8")
        print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
